### ISSUE TITLE
2.0.0 Release Checklist

### ISSUE THREAD

**Issue by malcolmrebughini** [goshippo/shippo-python-client#51]
- [x] Remove usages of `async` (#47 )
- [x] Drop support for Python < 3.5 (#45 )
- [x] Update docs and add "Migrating to v2" section
- [x] Force default api_version to `2018-02-08`
- [ ] Setup new CI

**Comment by Koeng101** [comment]
Could we get the git version pushed to pypi soon? I can install the package locally with `pip install -e .` , but still fails when I try to install it with pip. This is pretty inconvenient for deploying apps with heroku. Thanks!

**Comment by malcolmrebughini** [comment]
@Koeng101 We have published version `2.0.0rc1` to pypi. Just tried installing with `pip install -I shippo==2.0.0rc1` and it worked. 

If you were installing this version and getting an error, can you give more info on the error you are encountering? 

Thanks!

**Comment by goblinJoel** [comment]
@malcolmrebughini How safe is this version to switch to? We're upgrading to Python 3.7, and of course shippo 1 doesn't work. We're only using it for address validation and for tracking. Are there breaking changes?

**Comment by malcolmrebughini** [comment]
@goblinJoel I would say it is fairly safe, usage for address and tracking hasn't been touched (other than the change to the async parameter). There's a breaking change to config that is explained in https://github.com/goshippo/shippo-python-client#migrating-to-v2 

I cannot make promises that there won't be breaking changes between 2.0.0rc1 and the final release, but if more breaking changes appear they will be documented in the readme.

**Comment by goblinJoel** [comment]
Thanks for the response! I checked the diff between the releases, and I noticed that note about the config change, so combined with what you're saying, it sounds like it should be a pretty straightforward update.

**Comment by vsoch** [comment]
Thanks for providing this release candidate! I'm looking forward to seeing updates, and we can definitely use the release candidate in the meantime.

**Comment by hwangm** [comment]
Version 2.0.0 has been released today. No new breaking changes other than the ones in 2.0.0rc1
